### ISSUE TITLE
Panic when previewing .zprofile

### ISSUE THREAD

**Issue by kylepollina** [wvanlint/twf#1]
Hey, wanted to try this out as it looked nice. Ran into an issue looking through my home directory.
Looks like it panicked when I scrolled over my .zprofile

Heres the stacktrace:

```
panic: Terminal: exit status 1, stacktrace: goroutine 1 [running]:
runtime/debug.Stack(0xc00014f5c0, 0x1332e60, 0xc00000fa00)
	/usr/local/Cellar/go/1.14.3/libexec/src/runtime/debug/stack.go:24 +0x9d
github.com/wvanlint/twf/internal/terminal.(*Terminal).StartLoop.func1(0xc00014fcc8)
	/Users/kylepollina/go/src/github.com/wvanlint/twf/internal/terminal/terminal.go:187 +0x57
panic(0x1332e60, 0xc00000fa00)
	/usr/local/Cellar/go/1.14.3/libexec/src/runtime/panic.go:969 +0x166
github.com/wvanlint/twf/internal/views.(*previewView).Render(0xc000072230, 0x2, 0x34, 0x1b, 0x30, 0xc000358501, 0x51e, 0xa0)
	/Users/kylepollina/go/src/github.com/wvanlint/twf/internal/views/preview_view.go:55 +0x43e
github.com/wvanlint/twf/internal/terminal.(*Terminal).render(0xc000122090, 0xc00014fe40, 0x3, 0x3)
	/Users/kylepollina/go/src/github.com/wvanlint/twf/internal/terminal/terminal.go:147 +0x267
github.com/wvanlint/twf/internal/terminal.(*Terminal).StartLoop(0xc000122090, 0xc00007ef90, 0xc00014fe40, 0x3, 0x3, 0x0, 0x0)
	/Users/kylepollina/go/src/github.com/wvanlint/twf/internal/terminal/terminal.go:239 +0x38b
main.main()
	/Users/kylepollina/go/src/github.com/wvanlint/twf/cmd/twf/main.go:69 +0x599


goroutine 1 [running]:
main.main()
	/Users/kylepollina/go/src/github.com/wvanlint/twf/cmd/twf/main.go:72 +0x925
```

**Comment by wvanlint** [comment]
Thanks for trying it out and reporting the error!

Aside from some better error handling, it seems like the preview command returned `exit status 1`. Internally, it executes something similar to `bash -c "cat {}"` or what the `--previewCmd` is set to, with `{}` being replaced by the filename. Did you set the `--previewCmd` to something and if so, to what? Do you maybe not have `bash` installed? It's probably better not to assume that that is installed.

**Comment by wvanlint** [comment]
I ran into a similar issue when previewing files that I didn't have permission to read, I changed it so any preview errors will be shown in the window. Could you run `go get -u github.com/wvanlint/twf/cmd/twf` and see if that fixes it?

**Comment by wvanlint** [comment]
Closing now but feel free to reopen the issue if you see this happening again! Thanks again for reporting the error!
