### ISSUE TITLE
twf should error on bad argument to -locateDir

### ISSUE THREAD

**Issue by wwalker** [wvanlint/twf#12]
Passing `-locateCmd` a command that doesn't exist should fail with an error.

```
2020-06-07 21:36:00 - wwalker@plutonium:~ ✓ $ twf -locateCmd juhytgtr
2020-06-07 21:37:35 - wwalker@plutonium:~ ✓ $ 
```

**Comment by wvanlint** [comment]
This won't be able to fail immediately on start-up, since it needs to be interpreted by the shell, but should fail when used now.

**Comment by wwalker** [comment]
Verified as Fixed!!
