### ISSUE TITLE
Ignore node_modules when search

### ISSUE THREAD

**Issue by dinhmai74** [wvanlint/twf#3]
I wish I can ignore node_modules when I search, it scan all files in root folder now. Thank for you help.

**Comment by wvanlint** [comment]
Thanks for reporting! Is this issue for ignoring paths in the tree view or in `fzf` when locating a file using the `/` key (default keybinding)? In case it is the latter, you can configure `fzf` to ignore paths similar to here: https://github.com/junegunn/fzf#respecting-gitignore.

**Comment by dinhmai74** [comment]
Thank @wvanlint, I didn't config fzf. Now it works.
