### ISSUE TITLE
Jump to cursor after selecting a file with external tool 

### ISSUE THREAD

**Issue by wwalker** [wvanlint/twf#5]
When I use fzf (/) to select a file, the preview window is properly populated, but the tree view doesn't move such that where I am in the tree is visible.

It does jump to that area when I hit j or k.

**Comment by wvanlint** [comment]
I can reproduce the issue, it seems the tree doesn't scroll to the right point. Will fix soon, thanks for reporting! :)

**Comment by wvanlint** [comment]
I believe this should be fixed now after upgrading with `go get -u github.com/wvanlint/twf/cmd/twf` or `brew reinstall --HEAD wvanlint/twf/twf`. Let me know if you still have any issues though!

Thanks again for checking out the project and reporting the issues!

**Comment by wwalker** [comment]
asciinema of what I'm seeing attached
[twf-2.json.gz](https://github.com/wvanlint/twf/files/4743735/twf-2.json.gz)
