### ISSUE TITLE
Unable to bind ctrl-down

### ISSUE THREAD

**Issue by paw-lu** [wvanlint/twf#6]
Really cool work! Thanks for sharing!

I seem unable to bind `"ctrl-down"`.

```sh
❯ twf --bind="ctrl-down::preview:down" 
invalid value "ctrl-down::preview:down" for flag -bind: Can't parse event: ctrl-down
```

Seems `"down"` and `"ctrl-a"` work, but `"ctrl-down"` (and `"up"`) don't seem to be parsed.

**Comment by wvanlint** [comment]
Thanks for trying out the project!

I added support for some additional keys: `"shift-up"`, `"shift-down"`, `"shift-left"`, `"shift-right"`, `"ctrl-up"`, `"ctrl-down"`, `"ctrl-left"`, `"ctrl-right"`. It seems like only some terminals support it though (Terminal.app didn't work for me but iTerm did.). Let me know if you still see something wrong after updating with `go get -u github.com/wvanlint/twf/cmd/twf` or `brew reinstall --HEAD wvanlint/twf/twf`.

**Comment by paw-lu** [comment]
The `shift` ones work for me! But the `ctrl` ones do not on my end (macOS Hyper). `ctrl` + `up/down/left/right` is honestly a pretty bad key combo to map on macOS anyways 😅 since 3/4 of them are used by the system.

I no longer get the parsing error though. So I'm going to close the issue (if that's cool with you).

Again, thanks! Looking forward to seeing this project develop.
