### ISSUE TITLE
Binding shift-down causes hard lock

### ISSUE THREAD

**Issue by paw-lu** [wvanlint/twf#7]
Running

```sh
❯ twf --bind="shift-down::preview:down"
```

will work and launch the UI, but if you try to invoke the assigned binding (`"shift-down"`), the terminal will lock up and no longer respond to commands.

Again, great work!

**Comment by wvanlint** [comment]
I moved around some synchronization so this shouldn't lock anymore.

Note though that currently the `--bind` flag overrides all keybindings so the command in your example would only have one keybinding. A more user-friendly configuration is definitely on my list to work on. In the meantime, you can copy the default keybindings from `twf --help` and adjust them (and maybe put them in an alias). 

```sh
twf --bind="P::tree:parent;tree:close,enter::tree:selectPath;quit,k::tree:prev,shift-down::preview:down,shift-up::preview:up,o::tree:toggle,q::quit,ctrl-c::quit,esc::quit,j::tree:next,O::tree:toggleAll,p::tree:parent,/::tree:locateExternal"
```

Let me know if you see the same issue or anything else pop up. Thanks again for checking this out and reporting the issues! Really glad you like it :)

**Comment by paw-lu** [comment]
Yeah this seems perfect now. Thanks for the fix. I'll close this!
