### ISSUE TITLE
twf starts showing an open directory that is not open

### ISSUE THREAD

**Issue by wwalker** [wvanlint/twf#9]
wvanlint , again, thanks for a very cool ap !

Running 
```
twf
```
shows only one line:
```
▼ wwalker
```

The arrow indicates the directory is "open"; but, it isn't "open" nothing is below.

Hitting `o` twice works

or

Hitting `j` works too.

Also, it works right when I start twf with an unused argument comes up correctly:
```
twf asdfzxcv
```
shows correctly:
```
▼ wwalker
  ▶ ....
  ▶ .....
  ▶ .Skype
  ▶ .TeamSpeak 3
  ▶ .ansible
  ▶ .arduino15
  ▶ .aspera
  ▶ .audacity-data
  ▶ .aws
  ▶ .bashrc.d
```

**Comment by wvanlint** [comment]
After experimenting, I noticed there were some interesting filesystem cases that weren't handled yet, such as symbolic link loops and permission errors. Those should be handled better now, and any other errors are now surfaced. Thanks again for reporting the issues and I'm glad to hear you like the project! Let me know if you still run into this issue after updating with `go get -u github.com/wvanlint/twf/cmd/twf` or `brew reinstall --HEAD wvanlint/twf/twf`!

**Comment by wwalker** [comment]
This tests fixed for me, Thanks!
